services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "playlists"
      MYSQL_USER: "playlists"
      MYSQL_PASSWORD: "PLUGtoPLAYlists"
      MYSQL_ROOT_PASSWORD: "SAMIsells@123"
    volumes:
      - mysql_data:/var/lib/mysql

  plugtoplaylist:
    # REPLACE 'your-docker-username' with your actual Docker Hub username
    image: venihost/plugtoplaylist:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "80:3000" # Maps standard web port 80 to the app's internal port 3000
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      DATABASE_URL: "mysql://playlists:PLUGtoPLAYlists@mysql:3306/playlists"

      # NextAuth
      NEXTAUTH_URL: "https://plugtoplaylists.com"
      NEXTAUTH_SECRET: "VENIhost123!@#"

      # App URLs
      NEXT_PUBLIC_APP_URL: "https://plugtoplaylists.com"
      NEXT_PUBLIC_SUPPORT_EMAIL: "support@plugtoplaylists.com"
      SITE_NAME: "PlugToPlaylist"

      # Stripe (Must be production keys)
      STRIPE_SECRET_KEY: "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"
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_live_51SzGAJPUOXCDodz5uPaGrcBaRjCRCfujHw0MN4xkjRRSg9ZMB2eflDrSYA4A3kyJeqSwslrhD3cogWawMX5pcm1D00G1qjdQfo"
      STRIPE_WEBHOOK_SECRET: "your_stripe_webhook_secret"

      # Email (SMTP Production Settings)
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USER: "info.venihost@gmail.com"
      SMTP_PASS: "qmgx nqga klfm fshp"
      ADMIN_EMAIL: "admin@plugtoplaylists.com"

      # Music APIs
      SPOTIFY_CLIENT_ID: "8f5e092b94ff424d8726c2e9ba63e699"
      SPOTIFY_CLIENT_SECRET: "9de6de97449c443f8ca5fc667af71fbb"
      YOUTUBE_API_KEY: "AIzaSyDZI381Qhqra93bYzv7wb8WAQPUrOzg1Xo"

      # Security
      NEXT_PUBLIC_TURNSTILE_ENABLED: "true"
      NEXT_PUBLIC_TURNSTILE_SITE_KEY: "0x4AAAAAAC8jF0rKPraNPYE5"
      TURNSTILE_SECRET_KEY: "0x4AAAAAAC8jFx5KL4NN8h3qg6UTbzQ7tAw"
    # Optionally use a separate .env file for secrets
    # env_file:
    #   - .env.production

volumes:
  mysql_data:
